### ISSUE TITLE
Révision de la traduction en français des 30 dernières slides

### ISSUE THREAD

**Issue by bchhun** [bchhun/llc-intro-to-python#2]

**Comment by guibergeron** [comment]
Ligne 44: les «fichiers»
Ligne 96: de précieuses «informations»
Lignes 109 et 155: en anglais ou en fançais?
Ligne 208:  à titre de «référence»
Ligne 276: les «parenthèses»
Ligne 396: il «arrondit»
Ligne 429: va vous être = vous sera
Ligne 535: un message «demandant» (?)
Ligne 536: and pèse = et appuie
Ligne 551: des petites «parties»
Ligne 553 est encore en anglais
Ligne 555: «Faites» un clic-droit
Ligne 645: peut «servir»

**Comment by bchhun** [comment]
Je regarde cela right now @guibergeron

**Comment by bchhun** [comment]
Merci @guibergeron !
