### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by KBoisvert** [bchhun/llc-intro-to-python#3]
Slide1: unzip les fichier (ajouter un s à fichier), ouvrir slide.html (slide-fr.html)
Slide3: receuillant (recueillant), précieuses information (+s à informations)
Slide4: conditionalle (conditionnel)
slide25: L'utilisateur entre quelque chose and pèse sur entré 1  : et pèse
slide26: Créons un ensemble (créons ensemble) et enlever le para en anglais
slide27: automatiquemeent  enlever un e
slide47: toutes les instructions (Toutes)
slide53: So far, we've used small examples to practice using CSV files and recognizing patterns.  pas certaine si c'est la ligne en-dessous ou ?
slide56: très pratique Très : majuscule
slide 59: titre de la formation à mettre en français

**Comment by bchhun** [comment]
Merci @KBoisvert je corrige ça demain.

**Comment by bchhun** [comment]
Merci @KBoisvert je viens de faire le tour de tes correctifs !
