### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by KBoisvert** [bchhun/llc-intro-to-python#5]
première slide, unzip les fichiers de l'apprenti.e  (enlever le point)

Slide:21 >>> aujourdhui = "samedi"

> > > print("Aujourdhui, nous sommes " + today)
> > > Aujourdhui, nous sommes samedi
> > > (var se nomme aujourd'hui mais est utilisé comme today)

Je suis rendu à la slide 40, je continue demain je dors debout!

**Comment by bchhun** [comment]
tant pis. je les ai corrigés tout de suite car ça me tentait pas d'attendre jusqu'à tantôt.
